# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, attoparsec, cereal, filepath, processExts }:

cabal.mkDerivation (self: {
  pname = "disk-info";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ attoparsec cereal filepath processExts ];
  meta = {
    description = "maintain checksums for the files on a disk";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
